### ISSUE TITLE
An update must have the same type (float64)

### ISSUE THREAD

**Issue by LaiPiXiong** [zcyang/imageqa-san#12]
On my system, if I defined a float variable, it's default type is float64.  When I run "san_att_conv_twolayer.py", there shows error: 'An update must have the same type as the original shared variable (shared_var=conv_unigram_b, shared_var.type=TensorType(float32, vector), update_val=Elem
wise{sub,no_inplace}.0, update_val.type=TensorType(float64, vector)).' What can I do for this error?

**Comment by Adityakunwar** [comment]
@MloveDaxiong any updates for this error ?

**Comment by LaiPiXiong** [comment]
@Adityakunwar Oh, It's OK, I am sorry, I didn't see this before. It's because my python is 64bit. And I define a CONSTANT which in format float32.  It works.
